name: auto-changelog
on:
  pull_request:
    types: [opened]
jobs:
  add_changelog:
    runs-on: ubuntu-latest
    env:
      changelog_filename: CHANGELOG.md
    steps:
    - name: Checkout repo 
      uses: actions/checkout@v3
    - name: Checkout PR branch  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr checkout ${{ github.event.pull_request.number }}
    - name: Check for existing file
      run: test -f ./changelog.md || touch CHANGELOG.md
    - name: Add version and PR title at the beginning
      run: echo "PATCH\n${{github.event.pull_request.title}}\n\n" | cat - $changelog_filename > temp && mv temp $changelog_filename
    - name: Commit changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update changelog with version and title"
        git push
