name: auto-changelog
on:
  pull_request:
    types: [opened]
jobs:
  add_changelog:
    runs-on: ubuntu-latest
    env:
      changelog_filename: CHANGELOG.md
    steps:
    - name: Checkout repo 
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Check for existing file
      run: test -f ./changelog.md || touch CHANGELOG.md
    - name: add version and PR title at the beginning
      run: line=$(head -n 1 $changelog_filename | tr '[:lower:]' '[:upper:]') && [[ $line = PATCH || $line = MINOR || $line = MAJOR ]]; [[ $? -eq 0 ]] && echo "FILE ALREADY CONTAINS METADATA" || (echo "PATCH\n${{github.event.pull_request.title}}\n\n" | cat - $changelog_filename > temp && mv temp $changelog_filename)
    - name: Commit changelog
      run: |
        git config --global user.name ${{github.event.pull_request.user.name}}
        git config --global user.email ${{github.event.pull_request.user.email}}
        git commit -am "Automated Changelog"
        git push
