name: auto-changelog
on:
  pull_request:
    types: [opened]
jobs:
  add_changelog:
    runs-on: ubuntu-latest
    env:
      changelog_filename: CHANGELOG.md
    steps:
    - name: Checkout repo 
      uses: actions/checkout@v3
    - name: Checkout PR branch  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr checkout ${{ github.event.pull_request.number }}
    - name: Get changed files
      id: files
      uses: Ana06/get-changed-files@v1.2
    - name: Check if Changelog file is in PR diff
      id: is_changelog_updated
      run: |
        is_changelog_updated=0
        for changed_file in ${{ steps.files.outputs.all }}; do
        if [[ ${changed_file} == *"CHANGELOG.md" ]]
          then is_changelog_updated=1
          fi
        done
        echo ${is_changelog_updated}
    - name: Create Changelog file if it does not exist
      if: ${{ steps.is_changelog_updated == 0 }}
      run: test -f ./changelog.md || touch CHANGELOG.md
    - name: Add version and PR title at the beginning
      if: ${{ steps.is_changelog_updated == 0 }}
      run: echo -e "PATCH\n${{github.event.pull_request.title}}\n\n" | cat - $changelog_filename > temp && mv temp $changelog_filename
    - name: Commit changelog
      if: ${{ steps.is_changelog_updated == 0 }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update changelog with version and title"
        git push
