name: write-release-notes-post
on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:
jobs:
  write_blog_post:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v1.0.1
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Checkout branch
        run: |
          git checkout -b blog-post
      - name: Read Changelog for the last month
        id: last_month_changelog
        run: |
          while read -r line
          do
            [ -z "$line" ] && continue
            date=$(echo $line | rev | cut -d " " -f 1 | rev)
            month=$(echo $date | cut -d "-" -f 2)
            [[ $month -eq $(date +'%m') ]] && result="${result}\n${line}"
          done < ./CHANGELOG.md
          echo "result=${result}" >> $GITHUB_OUTPUT
      - name: Call OpenAI API
        id: call_openai
        run: |
          chmod +x ./scripts/call_open_ai.sh
          echo "result=$(./scripts/call_open_ai.sh ${{ steps.last_month_changelog.outputs.result }} ${{ secrets.OPEN_AI_TOKEN }})" >> $GITHUB_OUTPUT
        shell: bash
      - name: Calculate previous month
        id: calc_prev_month
        run: |
          echo "result=$(date --date="$(date +%Y-%m-%d) -1 month" +%B)" >> $GITHUB_OUTPUT
      - name: Add blog file
        run: |
          year=$(date +%Y)
          month=${{ steps.calc_prev_month.outputs.result }}
          mkdir ./blog/content/blog/${year}_${month}
          echo -e "---\ntitle: ${month}\ndate: '$(date +'%Y-%m-%d')'\ndescription: '${month} release notes'\n---\n${{ steps.call_openai.outputs.result }}" > ./blog/content/blog/${year}_${month}/index.md
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add ${{ steps.calc_prev_month.outputs.result }} blog post"
          git push --set-upstream origin blog-post
      - name: Create PR
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: blog-post
          target_branch: main
          title: ${{ steps.calc_prev_month.outputs.result }} release notes blog post
          body: '**Automated pull request**'
